linters:
  # Enable all available linters.
  # Default: false
  disable-all: true
  disable:
    - typecheck
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - godox
    - goerr113
    - goheader
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

linters-settings:
  wsl:
    strict-append: false
    enforce-err-cuddling: true

  gomnd:
    # Values always ignored: "1", "1.0", "0" and "0.0"
    # Default: []
    ignored-numbers:
      - '2'
    ignored-files:
      - 'internal/http/http.go'
